# Dashboard lovelace via yaml
# Add this file to /config
# Write this code to configuration.yaml:
# lovelace:
#   mode: yaml

views:
  - title: my-PV Dashboard
    path: view
    cards:
      - type: vertical-stack
        cards:
          - type: gauge
            entity: sensor.ac_elwa_2_1_temperatur_1
            severity:
              green: 40
              yellow: 50
              red: 70
          - type: history-graph
            entities:
              - entity: sensor.ac_elwa_2_1_frequency
              - entity: sensor.ac_elwa_2_1_temperatur_1
            hours_to_show: 1
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle   
            entity: switch.ww1boost_switch
            icon: mdi:water-boiler-auto